= Zadania

== Podstawy obsługi

=== Zadanie 1. Stworzenie repozytorium

. Załóż konto na https://gitlab.com
. Stwórz repozytorium kodu
. Pobierz repozytorium do lokalnego katalogu

=== Zadanie 2. Dodanie MR
. Stwórz nowego brancha
. Wypchnij go do repozytorium
. Utwórz MR

=== Zadanie 3. Code review
. Dodaj uczestników szkolenia do projektu jako developerów
. Poproś uczestników o code review

=== Zadanie 4. Integracja ze Slack
. Dodaj aplikacje GitLab do Slacka
. Skonfiguruj aplikację w taki sposób, żeby wszystko wysyłała na publiczny kanał stworzony przez Ciebie

=== Zadanie 5. Dodanie projektu aplikacji
. Wypchnij do repozytorium jakikolwiek projekt aplikacji (w taki języku, w jakim czujesz się swobodnie)

=== Zadanie 6. Opcje mergowania MR
. Stwórz kilka nowych MR
. Spróbuj je zmergować z różnymi opcjami
. Jaki efekt uzyskałeś?

== Instalacja i konfiguracja

== Zadanie 1. Zainstaluj GitLab Runnera

. Wykonaj następujące polecenia
[source,bash]
----
curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
sudo apt-get install gitlab-runner
----

=== Zadanie 2. Skonfiguruj 2 runnery

[IMPORTANT]
Zainstalowanie runnerów jako root (z `sudo` lub po zalogowaniu jako user root, np. `sudo -Hi`) nie wymaga ich uruchomienia poleceniem `gitlab-runner run`

. Załóż konto na stronie gitlab.com
. Utwórz repozytorium
. Przejdź do konfiguracji repozytorium
. Przejdź do zakładki CI/CD
. Przejdź do Runners
. Wyłącz shared runnery i dodaj 2 nowe runnery
* Operating systems: Linux
* Runner 1:
** Tags: linux, shared
** Run untagged jobs: true
* Runner 2:
** Tags: linux, docker
. Postępuj zgodnie z instrukcją na ekranie
* Runnera 1 uruchom jako `shell`
* Runnera 2 uruchom jako `docker`

== Pipeline

=== Zadanie 1. Uruchomienie pierwszego Pipeline

. Stwórz w edytorze wizualnym plik `.gitlab-ci.yml`
. Dodaj pierwszy pipeline

[source,yaml]
----
stages:
  - build

build-job:
  stage: build
  script:
    - echo "Hello World!"
----

[start=3]
. Uruchom pipeline
. Sprawdź logi wykonania pipeline i sprawdź, czy pojawił się napis `Hello World!`

=== Zadanie 2. Budowanie aplikacji Spring Boot

. Ściągnij przykładowy projekt ze strony start.spring.io (Maven)
. Zacommituj go do repozytorium
. Zmień wywołanie `echo` na `mvn clean verify`
. Sprawdź, czy pipeline wykonał się poprawnie

==== Rozwiązanie

[source,yaml]
----
stages:
  - build

build-job:
  stage: build
  script:
    - mvn clean verify
----

=== Zadanie 3. Budowanie aplikacji na konkretnym obrazie Dockerowym

. Popraw poprzedni pipeline wskazując, z jakiego obrazu Dockerowego ma korzystać runner (możesz wskazać: `maven:3.9.2-eclipse-temurin-17`)
. Otaguj `build-job`, żeby korzystał z Runnera dockerowego

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
----

=== Zadanie 4. Testy

. Zmodyfikuj pipeline z poprzedniego zadania dodając do niego obsługę JUnit
. Uruchom pipeline
. Obejrzyj jak wyglądają testy JUnit
. Dodaj test, który failuje
. Uruchom pipeline
. Zobacz, jak wyglądają wyniki w momencie, kiedy część testów nie przechodzi

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
----

=== Zadanie 5. Warunkowe wykonanie kroków

. Dopisz krok, który wykona się tylko na branchu `dev`
. Stwórz brancha `dev`
. Sprawdź, czy krok się wykonał
. Użyj instrukcji `when: manual`
. Sprawdź efekt

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-job-dev:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Hello World!"
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
----

=== Zdanie 6. Merge request

. Stwórz krok, który wykona się w momencie stworzenia merge requesta — użyj do tego dokumentacji https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-job-dev:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Hello World!"
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-job-mr:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Hello World MR!"
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
----

=== Zadanie 7. Dodanie chache

. Dopisz cachowanie folderu `.m2/repository`
. Uruchom pipeline
. Sprawdź, czy znowu były ściągane artefakty

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

build-job-dev:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Hello World!"
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
----

=== Zadanie 8. Zapisanie artefaktu

. Dopisz zapisywanie artefaktu
. Sprawdź, czy artefakt się zapisał

==== Rozwiązanie

[source,yaml]
----
image: maven:3.9.2-eclipse-temurin-17

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  script:
    - mvn clean verify
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/*.jar

build-job-dev:
  stage: build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
  script:
    - echo "Hello World!"
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/*.jar
----
