= Szkolenie CI/CD z wykorzystaniem Jenkinsa i GitLaba
:author: Juliusz Marciniak
:imagesdir: ./images

Szkolenie z podstaw CI/CD. Po szkoleniu będziecie wiedzieć, czym jest CI/CD. Nauczycie się definiować pipeline w narzędziu Jenkins i GitLab.

== O trenerze

Imię i nazwisko: Juliusz Marciniak

Zawód: Programista, DevOps, TechLead

Doświadczenie: 10 lat

Technologie:

* Java, Spring
* Jenkins, GitLab, Nexus
* Docker, Kubernetes

Jestem programistą Java z 10-letnim stażem. W codziennej pracy zajmuję się tematami cloudowymi i Kubernetesowymi. Oprócz tego doglądam architektury aplikacji w swoich projektach. Jestem entuzjastą nowych rozwiązań i technologii. Zwracam dużą uwagę, by rzeczy wdrażane przeze mnie były przemyślane i spójne. Czasami też programuję... i rekrutuję.

== Agenda
=== Dzień 1
. Podstawy teoretyczne
. Narzędzia do CI/CD — dlaczego wybieramy konkretne rozwiązania, GitLab/Bamboo/Jenkins
. Jenkins
.. Podstawy teoretyczne
.. Instalacja i konfiguracja
.. Pluginy
.. Deklarowanie pipeline
. GitLab Runner
.. Instalacja i konfiguracja
.. Porównanie z Jenkinsem
.. Deklarowanie pipeline

=== Dzień 2
. Nexus
.. Podstawy teoretyczne
.. Instalacja i konfiguracja
. Integracja narzędzi w spójny sposób
. Wstęp do CI/CD w chmurze

=== Dzień 3
[IMPORTANT]
To są przykładowe problemy, możliwe, że części z nich nie zdążymy omówić, a może będziemy dokładać.

. Warsztat na faktycznych problemach organizacji

== Zasady
* Staramy się nie spóźniać
* Telefon odbieramy poza salą
* Jesteśmy aktywni
* Jeśli utknęliśmy na problemie podczas realizacji zadań – natychmiast informujemy
* Nie śmiejemy się z innych i nie krytykujemy pomysłów innych
* Każdy ma prawo do wyrażania swojej opinii
* Przerwa na kawę co 1-1,5h
* Przerwa obiadowa o 13:00


include::theory/README.adoc[leveloffset=1]

include::jenkins/README.adoc[leveloffset=1]

include::gitlab/README.adoc[leveloffset=1]

include::nexus/README.adoc[leveloffset=1]
