= Continuous Integration z wykorzystaniem Jenkins
:author: Juliusz Marciniak
:imagesdir: ./images

Continuous Integration (CI) to praktyka w dziedzinie rozwoju oprogramowania, która polega na regularnym, częstym łączeniu zmian dokonywanych przez programistów w centralnym repozytorium. Zdobędziecie wiedzę i umiejętności związane z implementacją tej praktyki przy użyciu narzędzia Jenkins, które jest jednym z popularnych narzędzi do automatyzacji procesów CI/CD.

== O trenerze

Imię i nazwisko: Juliusz Marciniak

Zawód: Programista, DevOps, TechLead

Doświadczenie: 10 lat

Technologie:

* Java, Spring
* Jenkins, GitLab, Nexus
* Docker, Kubernetes

Jestem programistą Java z 10-letnim stażem. W codziennej pracy zajmuję się tematami cloudowymi i Kubernetesowymi. Oprócz tego doglądam architektury aplikacji w swoich projektach. Jestem entuzjastą nowych rozwiązań i technologii. Zwracam dużą uwagę, by rzeczy wdrażane przeze mnie były przemyślane i spójne. Czasami też programuję... i rekrutuję.

== Agenda
=== Dzień 1
. Wstęp do CI/CD
. DevOps
. Narzędzia CI/CD
. Jenkins
.. Wprowadzenie
.. Architektura
.. Instalacja i konfiguracja
.. Zadania
.. Pluginy
.. Notyfikacje
. Integracja z Git
. Integracja z Maven
. Definiowanie przepływu pracy przy pomocy kodu

=== Dzień 2
. Definiowanie przepływu pracy przy pomocy kodu
. Testowanie
. Jenkins security
. Jenkins w kontekście Infrastruktury jako kodu (IaC)
. Jenkins w kontekście pracy z AWS

== Zasady
* Staramy się nie spóźniać
* Telefon odbieramy poza salą
* Jesteśmy aktywni
* Jeśli utknęliśmy na problemie podczas realizacji zadań – natychmiast informujemy
* Nie śmiejemy się z innych i nie krytykujemy pomysłów innych
* Każdy ma prawo do wyrażania swojej opinii
* Przerwa na kawę co 1-1,5h
* Przerwa obiadowa o 13:00


include::theory/README.adoc[leveloffset=1]

include::jenkins/README.adoc[leveloffset=1]
